backend:
  name: test-repo
  #name: git-gateway
  #branch: trunk

collections:
  - name: blog
    label: Blog
    folder: 'content/blog'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }